[package]
name = "transition-uniffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "transition_uniffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
transition-core.workspace = true
uniffi = { workspace = true }
thiserror.workspace = true

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["cli-bindgen"]

[features]
default = []
cli-bindgen = ["uniffi/cli"]
