/**
 * Generates src/styles/themes.css from the Android app's Compose sources.
 *
 * The shipped app is the source of truth for the palettes. Parsing
 * Palettes.kt / Color.kt / AppTheme.kt instead of transcribing hex by hand
 * means the web themes cannot silently drift from what users actually see.
 *
 * Run via `npm run gen:themes` (part of `npm run build`).
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const THEME_DIR = join(root, '..', 'android/app/src/main/java/com/douxev/eggshell/ui/theme');

const kt = async (f) => readFile(join(THEME_DIR, f), 'utf8');

/** `Color(0xFF8839EF)` -> `#8839EF`; keeps alpha as #RRGGBBAA when not opaque. */
function hex(argb) {
  const v = argb.toLowerCase().replace(/^0x/, '').padStart(8, 'f');
  const a = v.slice(0, 2);
  const rgb = v.slice(2);
  return a === 'ff' ? `#${rgb.toUpperCase()}` : `#${rgb.toUpperCase()}${a.toUpperCase()}`;
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** Extracts every `val Name: ColorScheme = xColorScheme( ... )` block. */
function parseSchemes(source) {
  const out = {};
  const re = /val\s+(\w+)\s*:\s*ColorScheme\s*=\s*(light|dark)ColorScheme\(/g;
  let m;
  while ((m = re.exec(source))) {
    const [, name, mode] = m;
    // Walk to the matching close paren so nested Color(...) calls are safe.
    let depth = 1;
    let i = re.lastIndex;
    for (; i < source.length && depth > 0; i++) {
      if (source[i] === '(') depth++;
      else if (source[i] === ')') depth--;
    }
    const body = source.slice(re.lastIndex, i - 1);
    const tokens = {};
    for (const t of body.matchAll(/(\w+)\s*=\s*Color\(\s*(0[xX][0-9a-fA-F]+)\s*\)/g)) {
      tokens[t[1]] = hex(t[2]);
    }
    out[name] = { mode, tokens };
  }
  return out;
}

/** Reads the AppTheme enum: id, label, isDark, and its ColorScheme val. */
function parseCatalogue(appThemeSrc) {
  const entries = [];
  for (const m of appThemeSrc.matchAll(
    /^\s{4}(\w+)\("([^"]+)",\s*"([^"]+)",\s*isDark\s*=\s*(true|false)\)/gm,
  )) {
    entries.push({ symbol: m[1], id: m[2], label: m[3], isDark: m[4] === 'true' });
  }
  const scheme = {};
  for (const m of appThemeSrc.matchAll(/AppTheme\.(\w+)\s*->\s*(\w+)\s*$/gm)) {
    scheme[m[1]] = m[2];
  }
  return { entries, scheme };
}

const rgba = (h, a) => {
  const v = h.replace('#', '');
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(v.slice(i, i + 2), 16));
  return `rgba(${r},${g},${b},${a})`;
};

/**
 * Non-M3 tokens the prototype's m3.css adds on top of the role tokens.
 * Compose has no equivalent, so they are derived from the scheme's own
 * colours rather than hard-coded per theme.
 */
function derived(t, isDark) {
  const primary = t.primary ?? '#6A4FA3';
  const onSurfaceVariant = t.onSurfaceVariant ?? '#49454E';
  return {
    '--primary-fixed-dim': t.inversePrimary ?? primary,
    '--success': isDark ? '#A6D3A0' : '#3F6A3F',
    '--success-container': isDark ? '#265225' : '#C2F0BF',
    '--on-success-container': isDark ? '#C2F0BF' : '#072100',
    '--scrim': isDark ? 'rgba(0,0,0,0.55)' : 'rgba(0,0,0,0.4)',
    '--shadow': isDark ? 'rgba(0,0,0,0.45)' : 'rgba(0,0,0,0.20)',
    '--chart-grid': rgba(onSurfaceVariant, 0.14),
    '--frame-bg': t.surface ?? '#FDF7FF',
    '--frame-border': t.outlineVariant ?? '#C9C4CE',
    '--state-hover': rgba(primary, 0.08),
    '--state-press': rgba(primary, isDark ? 0.14 : 0.12),
  };
}

// `scrim` is emitted from the derived table (Compose stores it opaque black).
const SKIP = new Set(['scrim']);

function block(selector, scheme, isDark) {
  const lines = [`${selector} {`];
  const width = 30;
  const push = (name, value) => lines.push(`  ${(name + ':').padEnd(width)}${value};`);
  for (const [k, v] of Object.entries(scheme.tokens)) {
    if (SKIP.has(k)) continue;
    push(`--${kebab(k)}`, v);
  }
  for (const [k, v] of Object.entries(derived(scheme.tokens, isDark))) push(k, v);
  lines.push('}');
  return lines.join('\n');
}

const [colorSrc, palettesSrc, appThemeSrc] = await Promise.all([
  kt('Color.kt'),
  kt('Palettes.kt'),
  kt('AppTheme.kt'),
]);

const schemes = { ...parseSchemes(colorSrc), ...parseSchemes(palettesSrc) };
const { entries, scheme: symbolToScheme } = parseCatalogue(appThemeSrc);

const out = [
  '/* ============================================================',
  '   Eggshell — app themes',
  '   GENERATED by scripts/gen-themes.mjs from the Android app:',
  '   ui/theme/{Color,Palettes,AppTheme}.kt — do not edit by hand.',
  '   ============================================================ */',
  '',
];

const catalogue = [];
for (const e of entries) {
  if (e.symbol === 'SYSTEM') continue; // follows the OS; already covered by :root + [data-theme=dark]
  const schemeName = symbolToScheme[e.symbol];
  const scheme = schemes[schemeName];
  if (!scheme) {
    console.warn(`[gen-themes] no ColorScheme found for ${e.symbol} (${schemeName}) — skipped`);
    continue;
  }
  out.push(`/* ${e.label} — ${e.isDark ? 'dark' : 'light'} */`);
  out.push(block(`[data-eggshell-theme="${e.id}"]`, scheme, e.isDark));
  out.push('');
  catalogue.push({ id: e.id, label: e.label, isDark: e.isDark, scheme: schemeName });
}

await writeFile(join(root, 'src/styles/themes.css'), out.join('\n'), 'utf8');

// The component layer needs the same catalogue at runtime (theme picker etc.).
const ts = [
  '// GENERATED by scripts/gen-themes.mjs — do not edit by hand.',
  '',
  'export interface EggshellTheme {',
  '  /** Stable id, matches the Android `AppTheme.id` and the CSS attribute value. */',
  '  id: string;',
  '  /** Human label as shown in the app\'s theme picker. */',
  '  label: string;',
  '  /** Whether the palette is a dark one. */',
  '  isDark: boolean;',
  '}',
  '',
  '/** Every palette the Eggshell app ships, in picker order. */',
  'export const THEMES: EggshellTheme[] = [',
  ...catalogue.map(
    (c) => `  { id: ${JSON.stringify(c.id)}, label: ${JSON.stringify(c.label)}, isDark: ${c.isDark} },`,
  ),
  '];',
  '',
  'export type EggshellThemeId =',
  ...catalogue.map((c) => `  | ${JSON.stringify(c.id)}`),
  '  ;',
  '',
];
await writeFile(join(root, 'src/themes.ts'), ts.join('\n'), 'utf8');

console.log(`[gen-themes] ${catalogue.length} themes -> src/styles/themes.css + src/themes.ts`);
